apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: grafana-selfsigned
  namespace: monitoring
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  grafana-selfsigned
  namespace: monitoring
spec:
  secretName:  grafana-cert-tls
  dnsNames:
    - "grafana.demo.com"
  issuerRef:
    name: grafana-selfsigned