apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: prometheus-selfsigned
  namespace: monitoring
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name:  prometheus-selfsigned
  namespace: monitoring
spec:
  secretName:  prometheus-cert-tls
  dnsNames:
    - "prometheus.demo.com"
  issuerRef:
    name: prometheus-selfsigned