## Nginx Ingress
## Follow https://devopscube.com/setup-ingress-kubernetes-nginx-controller/

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/rewrite-target: /
    #cert-manager.io/issuer: "letsencrypt-prod"
    #cert-manager.io/cluster-issuer: "letsencrypt-production"
    #acme.cert-manager.io/http01-edit-in-place: "true"
    #kubernetes.io/tls-acme: "true"
    #kubernetes.io/tls: "letsencrypt-prod"
spec:
  rules:
  # Use the host you used in your kubernetes Ingress Configurations
  - host: prometheus.demo.com
    http:
      paths:
      - backend:
          service:
            name: prometheus-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts: 
    - prometheus.demo.com
    secretName: prometheus-cert-tls
# ---
# apiVersion: v1 
# kind: Secret 
# metadata:
#   name: prometheus-secret 
#   namespace: monitoring
# data:
# # USe base64 in the certs
#   tls.crt: 
#   tls.key: