apiVersion: v1
kind: Secret
metadata:
  name: telegraf-secrets
  namespace: monitoring
type: Opaque
stringData:
  INFLUXDB_BUCKET: telegraf
  INFLUXDB_URL: http://10.109.144.19:8086
  #INFLUXDB_USER: admin
  #INFLUXDB_USER_PASSWORD: kraken
  INFLUX_TOKEN: 6gS5-9JiyOHUISvuvIrOyPJlayxd1mofmh3Bi8-CxgK8ASDiJBJRo-7brarwS8FND6XYDIDuJLtgBLRe1mOeuA==