#helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
#helm repo update

#helm upgrade --install nginx ingress-nginx/ingress-nginx -n infrastructure --create-namespace -f values-ingress.yaml

controller:
  service:
    externalTrafficPolicy: Local

